env:
  browser: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent: ["error", 2]
  semi: "off"
  space-before-function-paren: "off"
  eol-last: "off"